version: '3'
services:
  app:
    container_name: ${CONTAINER_NAME}
    image: ${DOCKER_IMAGE}
    restart: ${RESTART}
    volumes:
      - type: bind
        source: ${VOLUME}
        target: ${WORK_DIR}
      - type: bind
        source: ./logs
        target: /logs
    networks:
      - nft-market    
    build: 
      context: .
      dockerfile: ${DOCKER_FILE}
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE}
        VOLUME: ${VOLUME}
        WORK_DIR: ${WORK_DIR}
    environment:
    - "TEST=${TEST}"
    - "CONTAINER_NAME=${CONTAINER_NAME}"
    - "COMMAND=${COMMAND}"
    - "VOLUME=${VOLUME}"
    - "DOCKER_IMAGE=${DOCKER_IMAGE}"
    - "WORK_DIR=${WORK_DIR}"
    - "TZ=${TIMEZONE}"
    - "HOST=${NODEJS_ADDRESS}"
    - "PORT=${NODEJS_PORT}"
    - "DB_HOST=${DB_HOST}"
    - "DB_USER=${DB_USER}"
    - "DB_PASSWORD=${DB_PASSWORD}"
    - "DB_NAME=${DB_NAME}"
    - "TIMEOUT=${TIMEOUT}"
    - "PARTICLE_AUTHORIZATION_URL=${PARTICLE_AUTHORIZATION_URL}"
    - "PARTICLE_PROJECT_ID=${PARTICLE_PROJECT_ID}"
    - "PARTICLE_CLIENT_KEY=${PARTICLE_CLIENT_KEY}"
    logging:
      driver: "${LOG_DRIVER}"
      options:
        tag: "{{.Name}}"
    ports:
      - "127.0.0.1:${NODEJS_PORT}:${NODEJS_PORT}"
networks:
  nft-market:
    name: nft-market
    external: true
    
