version: '3'
services:
  app:
    container_name: ${CONTAINER_NAME}
    image: ${DOCKER_IMAGE}
    restart: ${RESTART}
    volumes:
      - type: bind
        source: ${VOLUME}
        target: ${WORK_DIR}
      - type: bind
        source: ./logs
        target: /logs
    networks:
      - nft-market    
    build: 
      context: .
      dockerfile: ${DOCKER_FILE}
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE}
        VOLUME: ${VOLUME}
        WORK_DIR: ${WORK_DIR}
    environment:
    - "TEST=${TEST}"
    - "CONTAINER_NAME=${CONTAINER_NAME}"
    - "COMMAND=${COMMAND}"
    - "VOLUME=${VOLUME}"
    - "DOCKER_IMAGE=${DOCKER_IMAGE}"
    - "WORK_DIR=${WORK_DIR}"
    - "TZ=${TIMEZONE}"
    - "SERVICE_PORT=${SERVICE_PORT}"
    - "SERVICE_ADDRESS=${SERVICE_ADDRESS}"
    logging:
      driver: "${LOG_DRIVER}"
      options:
        tag: "{{.Name}}"
    ports:
      - "127.0.0.1:${SERVICE_PORT}:${SERVICE_PORT}"
networks:
  nft-market:
    name: nft-market
    external: true
    
